### ISSUE TITLE
got a bug with the new terrain feature

### ISSUE THREAD

**Issue by KCGD** [tentone/nunuStudio#405]
Hey, the new terrain tool looks great! it works in the editor but when running the project it gives this error: `<img alt="terrain"style="width:300px;height:300px"src="https://fs.kcgdnetwork.cf/f/p7Y8"></img>`

hope this helps :)

**Comment by tentone** [comment]
Hello

I have tested on the web version maybe you are running some old files better to clean the browser cache press F12 then select the reload button with the right mouse button.

![Capture](https://user-images.githubusercontent.com/9158354/84571149-6253b800-ad89-11ea-9d72-52630114d6cf.PNG)

This should fix the issue.

Thanks a lot!

**Comment by KCGD** [comment]
@tentone Hi, i tried the hard reload with emptying cache and the bug still happens, I also reloaded a few different ways and made sure there's no cache. It only happens on projects with terrain.
Thanks!

**Comment by tentone** [comment]
I will take a closer look into it to figure out whats going on there. Thanks a lot.
